### ISSUE TITLE
SSH issue -  [Errno 2] No such file or directory: '\\Users\\usename\\.ssh\\known_hosts'

### ISSUE THREAD

**Issue by szqianjunjing** [Simon0792/Woocommerce-uploader#1]
Traceback (most recent call last):
  File "F:\woocommerce-upload\Woocommerce-uploader-main\main.py", line 32, in <module>
    product_upload.uploadProducts(productData)
  File "F:\woocommerce-upload\Woocommerce-uploader-main\product_upload.py", line 201, in uploadProducts
    uploadImm()
  File "F:\woocommerce-upload\Woocommerce-uploader-main\scp_com.py", line 43, in uploadTempFiles
    client.load_host_keys(f'\\Users\\{username}\\.ssh\\known_hosts')
  File "E:\Program Files\Python310\lib\site-packages\paramiko\client.py", line 126, in load_host_keys
    self._host_keys.load(filename)
  File "E:\Program Files\Python310\lib\site-packages\paramiko\hostkeys.py", line 91, in load
    with open(filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '\\Users\\usename\\.ssh\\known_hosts'

**Comment by Simon0792** [comment]
Are you using windows?

**Comment by szqianjunjing** [comment]
Hi, Simon

Thanks for your reply. Yes. I am using windows
